export const widgetMap = {
  TITLE_WIDGET1: "TITLE_WIDGET1",
  TITLE_WIDGET2: "TITLE_WIDGET2",
  RADIO_WIDGET: "RADIO_WIDGET",
  RADIO_LIST_WIDGET: "RADIO_LIST_WIDGET",
  TEXT_AREA_WIDGET: "TEXT_AREA_WIDGET",
  INFO_WIDGET: "INFO_WIDGET",
  CHECKBOX_WIDGET: "CHECKBOX_WIDGET",
  CHECKLIST_WIDGET: "CHECKLIST_WIDGET",
  YOUTUBE_VIDEO_PLAYER: "YOUTUBE_VIDEO_PLAYER",
  IMAGE_CAROUSEL: "IMAGE_CAROUSEL",
  INPUT_WIDGET: "INPUT_WIDGET",
  LOCATION_INPUT_WIDGET: "LOCATION_INPUT_WIDGET",
  UPLOAD_IMAGE_WIDGET: "UPLOAD_IMAGE_WIDGET",
  MULTI_IMAGES_WIDGET: "MULTI_IMAGES_WIDGET"
};
